fix: fix building on C++20 - fix removal of shared_ptr.unique
mcneel/opennurbs pull request #33
Opened 2021-12-03 04:30 UTC by aminya

This replaces the removed shared_ptr.unique with .use_count() == 1
See this for the explanation
https:// en.cppreference.com/w/cpp/memory/shared_ptr/unique

Cherry-picked from #28

2021-12-28 19:41 UTC, sbaer commented on opennurbs_mesh.cpp
> +    if (false == item->m_mesh_sp.use_count() == 1)
This is really hard to read. I would recommend changing this to
`if (item->m_mesh_sp.use_count() != 1)`

2021-12-28 19:42 UTC, sbaer requested changes
This is really hard to read. I would recommend changing this to
`if (item->m_mesh_sp.use_count() != 1)`

2021-12-29 22:20 UTC, aminya commented
> This is really hard to read. I would recommend changing this to `if (item->m_mesh_sp.use_count() != 1)`

Fixed in https://github.com/mcneel/opennurbs/pull/33/commits/71e81b4db2c2f2f5ead2fc549f894328d07012c4

2021-12-30 00:40 UTC, sbaer approved these changes

2021-12-30 00:41 UTC, merged